# @format

architecture: "DiffFormer" # or "DiffFormer"
learning_rate: 0.003
max_iters: 400
batch_size: 64
save_every: 100
eval_every: 100
num_val_samples: 1000

# Dataset and model configuration
d_dim: 20
hidden_d_dim: 5
n_examples: 41
tau: 1.0
