# @format

architecture: "Transformer" # or "DiffFormer"
learning_rate: 0.003
max_iters: 400
batch_size: 32
save_every: 100
eval_every: 100
num_val_samples: 1000

# Dataset and model configuration
d_dim: 10
hidden_d_dim: 20
num_samples: 10000
n_examples: 5
tau: 1.0
