name: DiffXformer
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=11.0.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.11.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==24.2.0
      - blobfile==3.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorama==0.4.6
      - dataproperty==1.0.1
      - docker-pycreds==0.4.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - joblib==1.4.2
      - jsonlines==4.0.0
      - lm-eval==0.4.5
      - lxml==5.3.0
      - markupsafe==3.0.2
      - mbstrdecoder==1.1.3
      - more-itertools==10.5.0
      - multidict==6.1.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numexpr==2.10.2
      - numpy==2.1.2
      - omegaconf==2.3.0
      - packaging==24.2
      - pandas==2.2.3
      - pathvalidate==3.2.1
      - platformdirs==4.3.6
      - portalocker==3.0.0
      - propcache==0.2.1
      - psutil==6.1.0
      - pybind11==2.13.6
      - pycryptodomex==3.21.0
      - pytablewriter==1.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.11.6
      - rouge-score==0.1.2
      - sacrebleu==2.4.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentry-sdk==2.19.1
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.1
      - sqlitedict==2.1.0
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - torch==2.5.0
      - torchao==0.6.1
      - torchtune==0.4.0
      - tqdm-multiprocess==0.0.11
      - typepy==1.3.2
      - tzdata==2024.2
      - wandb==0.18.7
      - word2number==1.1
      - yarl==1.18.3
      - zstandard==0.23.0
